title: Dani Perez @ Github 
description: >- # this means to ignore newlines until "baseurl:"
  Dani Perez' corner in Github.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  daniperez

markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-feed

remote_theme: "mmistakes/so-simple-theme@3.2.0"
search_full_content: true
skin: "/assets/css/skins/light.css"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

permalink: /:categories/:title/
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

feed:
  path: atom.xml
footer_links:
  - title: Feed
    url: atom.xml
    icon: fa-lg fas fa-rss-square
