title: Dani Perez @ Github 
description: >- # this means to ignore newlines until "baseurl:"
  <description TBC>  
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  daniperez

markdown: kramdown

remote_theme: "mmistakes/so-simple-theme@3.2.0"
search_full_content: true
skin: "/assets/css/skins/light.css"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

plugins:
  - jekyll-paginate
  - jekyll-remote-theme

